# Generated by Django 5.1.7 on 2025-03-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_alter_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
